# Generated by Django 5.0.6 on 2024-06-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('review_text', models.TextField()),
                ('predicted_score', models.IntegerField()),
                ('satisfaction_response', models.CharField(max_length=50)),
            ],
        ),
    ]
